function e() {
  $SET_EXIT_HANDLER
  if declare -f ON > /dev/null; then
      echo "Continue"
      else
        echo "The function that keeps the OS on was not found. 
Your OS is corrupted, please re-install it."
        read -p "Press Enter to continue..." 2>/dev/tty
        exit 0
      fi
clear
MCMDB=0

  echo "                                                                                                    
                                                                                                    
                                                                                                    
                                              @@@@@                                                 
                                           @@@@@@@@@@@                                              
                                          @@@@@@@@@@@@@                                             
                                   @@@@@@@@@@@@@@@@@@@@@                                            
              @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                            
             @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                          
               @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                      
                 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                    
                   @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ @@@@@@@@@@@@                                   
                     @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@   @@@@@@@@@@@                                   
                     @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@    @@@@@@@@@@@@                                 
                    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@      @@@@@@  @@@                                
                    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@          @@@  @@@                               
                   @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@           @@@  @@@                              
                   @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@            @@@  @@@                             
                    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@             @@@  @@@                            
                    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@              @@@@  @@@                          
                     @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@               @@@  @@@                         
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@                 @@@  @@@                        
                        @@@@@@@@@@@@@@@@@@@@@@@@@@@@                 @@@  @@@                       
                          @@@@@@@@@@@@@    @@@@@@@@@                  @@@  @@@@                     
                                             @@@@@@@                   @@@@  @@@                    
                                                @@@@                     @@@  @@@                   
                                                 @@@                      @@@  @@@                  
                                                                           @@@ @@@@@@               
      LUMINOUS IS BOOTING                                                   @@@@@@@@@@@             
          PLEASE WAIT.                                                       @@@@@@@@@@             
                                                                             @@@@@@@@@@             
                                                                             @@@@@@@@@@             
                                                                            @@@ @@@@                
                                                                          @@@   @@@                 
                                                                          @@@  @@@                  
                                                                         @@@  @@@                   
                                                                        @@   @@@                    
                                                                      @@@   @@@                     
                                                                     @@@   @@@                      
                                                                    @@@   @@@                       
                                                                   @@@   @@@                        
                                                                  @@@   @@@                         
                                                                 @@@  @@@                           
                                                                @@@  @@@                            
                                                               @@@  @@@                             
                                                              @@@  @@@                              
                                                             @@@  @@@                               
                                                            @@@  @@@                                
                                            @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@              
                                          @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@              
                                          @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@              
                                            @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@              
                                                                                                    
                                                                                                    
                                                                                                    "
                                                                                                    if [ $cmd0m == "0" ]; then
                                                                                                    read -n1 -t 1 cmd0 2>/dev/tty
                                                                                                    fi

  clear
  cmd0m=0
if [ "$cmd0" == "M" ]; then
    clear
    echo "<INFO> Boot menu launched. [Time log was made: `date +%Y`-`date +%m`-`date +%d` `date +%H`:`date +%M`:`date +%S` ]
" >> CONFIG/Event-Log.log
    echo "<INFO> Boot menu launched. [Time log was made: `date +%Y`-`date +%m`-`date +%d` `date +%H`:`date +%M`:`date +%S` ]
" >> CONFIG/Info-Log.log
    echo "                                                                                                                                                                                                
                                                                                                    
                                                                                                    
                                              @@@@@                                                 
                                           @@@@@@@@@@@                                              
                                          @@@@@@@@@@@@@                                             
                                   @@@@@@@@@@@@@@@@@@@@@                                            
              @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                            
             @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                          
               @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                      
                 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                    
                   @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ @@@@@@@@@@@@                                   
                     @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@   @@@@@@@@@@@                                   
                     @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@    @@@@@@@@@@@@                                 
                    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@      @@@@@@  @@@                                
                    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@          @@@  @@@                               
                   @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@           @@@  @@@                              
                   @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@            @@@  @@@                             
                    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@             @@@  @@@                            
                    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@              @@@@  @@@                          
                     @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@               @@@  @@@                         
                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@                 @@@  @@@                        
                        @@@@@@@@@@@@@@@@@@@@@@@@@@@@                 @@@  @@@                       
                          @@@@@@@@@@@@@    @@@@@@@@@                  @@@  @@@@                     
                                             @@@@@@@                   @@@@  @@@                    
                                                @@@@                     @@@  @@@                   
                                                 @@@                      @@@  @@@                  
  ┏━  ┓ ┳┳┳┳┓┳┳┓┏┓┳┳┏┓  ━┓                                                 @@@ @@@@@@               
  ┃   ┃ ┃┃┃┃┃┃┃┃┃┃┃┃┗┓   ┃                                                  @@@@@@@@@@             
  ┗━  ┗┛┗┛┛ ┗┻┛┗┗┛┗┛┗┛  ━┛                                                   @@@@@@@@@@           
    ┳┓┏┓┏┓┏┳┓  ┳┳┓┏┓┳┓┳┳                                                      @@@@@@@@@@           
    ┣┫┃┃┃┃ ┃   ┃┃┃┣ ┃┃┃┃                                                       @@@@@@@@@@           
    ┻┛┗┛┗┛ ┻   ┛ ┗┗┛┛┗┗┛                                                        @@@@@@@@@           
                                                                                @@@@@@@@     
                                                                                @@@@@@@@   
                                                                               @@@@@@@@ 
     1-Bypass bootloader (Not recommended$exc)                                   @@@@@@@@@
     2-Re-install LUMINOUS OS                                                @@@@@@@@@
     3-Boot with custom loader (buggy)                                      @@@@@@@@@
     4-Continue booting                                                     @@@@@@@@@             
                                                                            @@@ @@@@                
                                                                           @@@  @@@                 
                                                                          @@@  @@@                  
                                                                         @@@  @@@                   
                                                                        @@   @@@                    
                                                                      @@@   @@@                     
                                                                     @@@   @@@                      
                                                                    @@@   @@@                       
                                                                   @@@   @@@                        
                                                                  @@@   @@@                         
                                                                 @@@   @@@                          
                                                                @@@   @@@                           
                                                               @@@   @@@                            
                                                              @@@   @@@                             
                                                             @@@   @@@                              
                                                            @@@   @@@                               
                                            @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@              
                                          @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@              
                                          @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@              
                                            @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
read -n1 BOOTMENU
    if [ "$BOOTMENU" == "1" ]; then
        clear
        Power=2
        ON
    elif [ "$BOOTMENU" == "2" ]; then
        curl -O https://raw.githubusercontent.com/SilentTheOG/SILENTOS-SERVER/main/SERVER.TMP
        touch FAILSAFE.SH
        cat SERVER.TMP > e.sh | rm SERVER.TMP
        echo "touch tmp.sh
echo \"./e.sh\" >> tmp.sh
./tmp.sh
rm tmp.sh
if [ -e \"e.sh\" ] && [ ! \"\$(wc -c < \"e.sh\")\" -gt 3 ]; then
./RECOVERY_SCRIPT.SH
else
./e.sh
fi" > FAILSAFE.SH
        ./FAILSAFE.SH
        elif [ "$BOOTMENU" == "3" ]; then
        cbl
    elif [ "$BOOTMENU" == "4" ]; then
        clear

elif [ "$BOOTMENU" == "d" ]; then
exec 2>/dev/tty
devm=1
echo "[SECRET] Developer mode enabled."
read

    else
        clear
        echo "Not an option!"
        sleep 1
        clear
    fi
fi

  if [ $setup == 1 ]; then
  clear
  check
  else
  echo ""
  fi
  line=$(sed -n '3p' "$file")
  if [ $line == 0 ]; then
  MCMDB=0
  else
  MCMDB=1
  fi
SIGNIN () {
  ALLOW=0
  line=$(sed -n '4p' "$file")
  if [ "$line" == "1" ]; then
  clear
    echo "Select profile:"
    line=$(sed -n '2p' "$file")
    echo "User 1 - $line"
    ALLOW=1

    line=$(sed -n '5p' "$file")
    if [ "$line" != "0" ]; then
      echo "User 2 - $line"
      ALLOW1=1
    else
      echo "User 2 not found."
      ALLOW1=0
    fi

    line=$(sed -n '6p' "$file")
    if [ "$line" != "0" ]; then
      echo "User 3 - $line"
      ALLOW2=1
    else
      echo "User 3 not found."
      ALLOW2=0
    fi

    MUL=0
    read -n1 MUL 2>/dev/tty
    clear

    if [ "$MUL" != "1" ] && [ "$MUL" != "2" ] && [ "$MUL" != "3" ]; then
      echo "
      Invalid input, try again."
      SIGNIN
    elif [ "$MUL" == "1" ]; then 
      MUL=1
    elif [ "$MUL" == "2" ]; then
      if [ "$ALLOW1" == "1" ]; then
        MUL=2
      else
        SIGNIN
      fi
    elif [ "$MUL" == "3" ]; then
      if [ "$ALLOW2" == "1" ]; then
        MUL=3
      else
        SIGNIN
      fi
    else
      MUL=1
    fi
  fi
}
line=$(sed -n '7p' "$file")
  if [ -z "$line" ] || [ $line == "" ]; then
  echo "0" >> CONFIG/CONFIG.CFG
  LO=1
  read -p "Press Enter to continue..." 2>/dev/tty
  fi
if [ $LO == 0 ]; then
SIGNIN
else
MUL=1
fi

  code=0
  $SET_EXIT_HANDLER


if [ ! -e "$file" ]; then
echo "<ERROR> One or more config file(s) was not found. [Time log was made: `date +%Y`-`date +%m`-`date +%d` `date +%H`:`date +%M`:`date +%S` ]
" >> CONFIG/Event-Log.log
echo "<ERROR> One or more config file(s) was not found. [Time log was made: `date +%Y`-`date +%m`-`date +%d` `date +%H`:`date +%M`:`date +%S` ]
" >> CONFIG/Error-Log.log
    printf "${RED}                                ......
                               :      :
                               :      :
                               :      : 
                               :      : 
                               :      : 
                               :      : 
                               :      : 
                               :      : 
                               :      : 
                               :      : 
                                ......

                                ......
                               :      :
                               :      :
                                ......
MISSING OS CONFIGURATION INFO!
CREATING CONFIG INFO.

"
printf "${BLUE}-Note: If you have MCMDB Mode on this will turn it off and you will need to turn it back on.${RED}"
echo "" > CONFIG/CONFIG.CFG
if [ -e "$file" ]; then
echo "
Sucess!"
./e.sh
else
echo "There has been an error creating the configuration file, you may still boot, however you will lose access to a number of features.
It is recommended to reinstall LUMINOUS OS."
read -p "Press Enter to continue..." 2>/dev/tty
printf "${NOCOLOR}"
clear
echo "<INFO> System booted. [Time log was made: `date +%Y`-`date +%m`-`date +%d` `date +%H`:`date +%M`:`date +%S` ]
" >> CONFIG/Event-Log.log
echo "<INFO> System booted. [Time log was made: `date +%Y`-`date +%m`-`date +%d` `date +%H`:`date +%M`:`date +%S` ]
" >> CONFIG/Info-Log.log
clear
   echo "    @@@@@         @@@@@    @@@@@      @@@@@@      @@@@@@      @@@@@@      @@@@@     @@@@        @@@@@@@@@       @@@@@@    @@@@@      @@@@@@@@@  
    @@@@          @@@@      @@@        @@@@@     @@@@@@        @@@@       @@@@@      @        @@@@     @@@@      @@@       @@      @@@@     @@  
    @@@@          @@@@     @@@        @@ @@@    @@ @@@        @@@@        @@ @@@    @@      @@@@       @@@@     @@@@      @@@      @@@@         
   @@@@          @@@@      @@@       @@  @@@   @@ @@@@        @@@@       @@  @@@@   @@      @@@@       @@@@     @@@      @@@        @@@@@       
   @@@@          @@@      @@@        @@  @@@ @@   @@@        @@@@        @@   @@@@ @@      @@@@       @@@@     @@@@      @@@          @@@@@@    
  @@@@          @@@@      @@@       @@@  @@@@@   @@@@        @@@        @@     @@@ @@      @@@@      @@@@@     @@@@     @@@             @@@@    
  @@@     @@@   @@@@     @@@        @@    @@@    @@@        @@@@        @@      @@@@       @@@@     @@@@       @@@      @@@      @@     @@@@    
@@@@@@@@@@@@      @@@@@@@@         @@@@        @@@@@@      @@@@@@     @@@@      @@@@         @@@@@@@@@          @@@@@@@@@       @@@@@@@@@@      
BACKUP LOADER."
    if [ $devm == "1" ]; then
echo "DEVELOPER MODE."
fi
if [ $MUL == 1 ]; then
line=$(sed -n '2p' "$file")
elif [ $MUL == 2 ]; then 
line=$(sed -n '5p' "$file")
elif [ $MUL == 3 ]; then
line=$(sed -n '6p' "$file")
else
line="UNKNOWN USER"
fi
rand=$((RANDOM % 3))
if [ "$rand" -eq 0 ]; then
  res="We hope you brought pizza$exc"
elif [ "$rand" -eq 1 ]; then
  res="How's your day going?"
else
  res="Hope you're doing well$exc"
fi
echo "Welcome, $line$exc $res"
if [ $MCMDB == 1 ]; then 
echo "Version 6.0$exc$exc$exc (BETA), contact skibiditoiletcumrocket67 on Discord for more details."
                       echo "Use command $quote2 for a list of commands
"
else
echo "Version 6.0$exc$exc$exc, contact skibiditoiletcumrocket67 on Discord for more details."
                       echo "Use command $quote2 for a list of commands
"
fi
ON
clear
fi




fi

echo "<INFO> System booted. [Time log was made: `date +%Y`-`date +%m`-`date +%d` `date +%H`:`date +%M`:`date +%S` ]
" >> CONFIG/Event-Log.log
echo "<INFO> System booted. [Time log was made: `date +%Y`-`date +%m`-`date +%d` `date +%H`:`date +%M`:`date +%S` ]
" >> CONFIG/Info-Log.log
./RECOVERY_SCRIPT.SH &
clear
echo "    @@@@@         @@@@@    @@@@@      @@@@@@      @@@@@@      @@@@@@      @@@@@     @@@@        @@@@@@@@@       @@@@@@    @@@@@      @@@@@@@@@  
    @@@@          @@@@      @@@        @@@@@     @@@@@@        @@@@       @@@@@      @        @@@@     @@@@      @@@       @@      @@@@     @@  
    @@@@          @@@@     @@@        @@ @@@    @@ @@@        @@@@        @@ @@@    @@      @@@@       @@@@     @@@@      @@@      @@@@         
   @@@@          @@@@      @@@       @@  @@@   @@ @@@@        @@@@       @@  @@@@   @@      @@@@       @@@@     @@@      @@@        @@@@@       
   @@@@          @@@      @@@        @@  @@@ @@   @@@        @@@@        @@   @@@@ @@      @@@@       @@@@     @@@@      @@@          @@@@@@    
  @@@@          @@@@      @@@       @@@  @@@@@   @@@@        @@@        @@     @@@ @@      @@@@      @@@@@     @@@@     @@@             @@@@    
  @@@     @@@   @@@@     @@@        @@    @@@    @@@        @@@@        @@      @@@@       @@@@     @@@@       @@@      @@@      @@     @@@@    
@@@@@@@@@@@@      @@@@@@@@         @@@@        @@@@@@      @@@@@@     @@@@      @@@@         @@@@@@@@@          @@@@@@@@@       @@@@@@@@@@      
BACKUP LOADER."
    if [ $devm == "1" ]; then
echo "DEVELOPER MODE."
fi
if [ $MUL == 1 ]; then
line=$(sed -n '2p' "$file")
elif [ $MUL == 2 ]; then 
line=$(sed -n '5p' "$file")
elif [ $MUL == 3 ]; then
line=$(sed -n '6p' "$file")
else
line="UNKNOWN USER"
fi
rand=$((RANDOM % 3))
if [ "$rand" -eq 0 ]; then
  res="We hope you brought pizza$exc"
elif [ "$rand" -eq 1 ]; then
  res="How's your day going?"
else
  res="Hope you're doing well$exc"
fi
echo "Welcome, $line$exc $res"
if [ $MCMDB == 1 ]; then 
echo "Version 6.0$exc$exc$exc (BETA), contact skibiditoiletcumrocket67 on Discord for more details."
                       echo "Use command $quote2 for a list of commands
"
else
echo "Version 6.0$exc$exc$exc, contact skibiditoiletcumrocket67 on Discord for more details."
                       echo "Use command $quote2 for a list of commands
"
fi
    Power=2
}
